"""
英语知识树 v2 — 课程标准对齐版

课程结构:
  语言知识: 词法(LEXA) / 句法(SYN) / 时态与语态(TVOI) / 非谓语动词(NFVB) / 虚拟语气(SUBM)
  语言技能: 听(SK-LIS) / 说(SK-SPE) / 读(SK-REA) / 说(SK-WRI)
  主题语境: 人与自我(TS-SELF) / 人与社会(TS-SOCI) / 人与自然(TS-NATR)
  语篇类型: DISC

与 english.py (v1) 无代码冲突 — v1 侧重题型模块(语法/词汇/阅读/完形/写作/听力),
v2 侧重课标维度(语言知识细分/语言技能/主题语境/语篇类型).
"""

from __future__ import annotations

from app.domains.knowledge.tree_seed.types import KnowledgeTreeSeed

ENGLISH_KNOWLEDGE_TREE_V2: list[KnowledgeTreeSeed] = [

    # ═══════════════════════════════════════════════════════════════════════════════
    # Level 2: 课程模块 (7)
    # ═══════════════════════════════════════════════════════════════════════════════

    KnowledgeTreeSeed(
        code="ENG-LEXA", name="词法", level=2, parent_code="ENG",
        description="词法知识: 名词/动词/形容词/副词/代词/数词/介词/连词/冠词的分类与用法",
        keywords=[
            "词法",
            "名词",
            "动词",
            "形容词",
            "词类",
            "parts of speech",
            "noun",
            "verb",
            "adjective",
            "morphology",
            "along with",
            "as well as",
            "blank",
            "blanks",
            "choose the best sentence",
            "coherence",
            "either or",
            "fill in",
            "fill in the blanks",
            "fill in the gap",
            "gap",
            "neither nor",
            "not only but also",
            "paragraph",
            "subject-verb agreement",
            "together with",
            "transition",
            "上下文",
            "主谓一致",
            "前缀",
            "句子还原",
            "合成",
            "后缀",
            "因果",
            "填空",
            "复现",
            "就近原则",
            "情感",
            "意义一致",
            "指代",
            "掌握其大意",
            "搭配",
            "构词法",
            "衔接",
            "补全短文",
            "词根",
            "转折",
            "选项",
            "通读下面",
            "逻辑",
            "阅读下面短文",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN", name="句法", level=2, parent_code="ENG",
        description="句法知识: 句子成分、基本句型、复合句(定语从句/状语从句/名词性从句)、特殊句式",
        keywords=["句法", "句子成分", "句型", "复合句", "特殊句式",
                  "syntax", "sentence pattern", "clause",
                  "sentence structure"],
    ),
    KnowledgeTreeSeed(
        code="ENG-TVOI", name="时态与语态", level=2, parent_code="ENG",
        description="八种核心时态与被动语态的构成、用法与辨析",
        keywords=[
            "时态",
            "语态",
            "被动",
            "时态辨析",
            "tense",
            "voice",
            "passive",
            "active",
            "tense and voice",
            "active voice",
            "agreement",
            "clause",
            "clauses",
            "ellipsis",
            "emphasis",
            "future tense",
            "grammar",
            "had been",
            "had done",
            "has been",
            "have been",
            "have done",
            "inversion",
            "is being",
            "non-finite",
            "nonfinite",
            "passive voice",
            "past perfect",
            "past tense",
            "present continuous",
            "present perfect",
            "simple past",
            "simple present",
            "subjunctive",
            "was being",
            "was done",
            "were done",
            "will be done",
            "will have",
            "一般现在",
            "主谓一致",
            "从句",
            "现在完成",
            "省略",
            "虚拟语气",
            "语法",
            "过去式",
            "非谓语",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-NFVB", name="非谓语动词", level=2, parent_code="ENG",
        description="动词不定式、动名词、现在分词、过去分词的用法与区别",
        keywords=[
            "非谓语",
            "不定式",
            "动名词",
            "分词",
            "non-finite",
            "infinitive",
            "gerund",
            "participle",
            "nonfinite verb",
            "being done",
            "doing",
            "done",
            "having been done",
            "having done",
            "non-finite verb",
            "past participle",
            "present participle",
            "to be doing",
            "to do",
            "to have done",
            "现在分词",
            "过去分词",
            "非谓语动词",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SUBM", name="虚拟语气", level=2, parent_code="ENG",
        description="虚拟语气在条件句、wish/suggest/demand等从句中的用法",
        keywords=[
            "虚拟语气",
            "if条件句",
            "wish",
            "subjunctive mood",
            "subjunctive",
            "hypothetical",
            "unreal condition",
            "I wish",
            "as if",
            "as though",
            "can",
            "could",
            "dare",
            "if I were",
            "if only",
            "it is time that",
            "may",
            "might",
            "modal verb",
            "must",
            "need",
            "ought to",
            "shall",
            "should",
            "will",
            "wish虚拟",
            "would",
            "would rather",
            "情态动词",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL", name="语言技能", level=2, parent_code="ENG",
        description="听、说、读、写四项语言技能的培养与训练",
        keywords=["语言技能", "听力", "口语", "阅读", "写作",
                  "language skills", "listening", "speaking",
                  "reading", "writing"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME", name="主题语境", level=2, parent_code="ENG",
        description="课标三大主题语境: 人与自我、人与社会、人与自然",
        keywords=["主题语境", "人与自我", "人与社会", "人与自然",
                  "thematic context", "theme", "topic",
                  "self and society", "man and nature"],
    ),
    KnowledgeTreeSeed(
        code="ENG-DISC", name="语篇类型", level=2, parent_code="ENG",
        description="记叙文、说明文、议论文、应用文、新闻报道、对话与访谈",
        keywords=["语篇", "文体", "语篇类型",
                  "discourse", "text type", "genre",
                  "narrative", "expository", "argumentative"],
    ),

    # ═══════════════════════════════════════════════════════════════════════════════
    # ENG-LEXA 词法 (L3: 9, L4: 21)
    # ═══════════════════════════════════════════════════════════════════════════════

    KnowledgeTreeSeed(
        code="ENG-LEXA-NOUN", name="名词", level=3, parent_code="ENG-LEXA",
        description="名词的分类、可数与不可数、单复数变化规则",
        keywords=["名词", "可数名词", "不可数名词", "复数",
                  "noun", "countable", "uncountable", "plural"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-NOUN-01", name="名词分类与可数性", level=4, parent_code="ENG-LEXA-NOUN",
        description="普通名词/专有名词、可数名词与不可数名词的判定与转化",
        keywords=["普通名词", "专有名词", "可数", "不可数",
                  "common noun", "proper noun", "countability"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-NOUN-02", name="名词单复数", level=4, parent_code="ENG-LEXA-NOUN",
        description="规则复数(-s/-es/-ies)、不规则复数、集体名词、不可数名词的量化表达",
        keywords=["单数", "复数", "不规则复数", "集体名词",
                  "singular", "plural", "irregular plural",
                  "collective noun"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-VERB", name="动词", level=3, parent_code="ENG-LEXA",
        description="动词的基本形式、时态变化、语态、动词分类(实义/系动词/助动词/情态动词)",
        keywords=["动词", "实义动词", "系动词", "助动词", "情态动词",
                  "verb", "action verb", "linking verb",
                  "auxiliary verb", "modal verb"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-VERB-01", name="动词基本形式与分类", level=4, parent_code="ENG-LEXA-VERB",
        description="动词原形/第三人称单数/过去式/过去分词/现在分词、实义动词与系动词区分",
        keywords=["动词形式", "第三人称单数", "过去式", "系动词",
                  "base form", "third person", "past tense",
                  "linking verb", "be/look/seem/feel"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-ADJ", name="形容词", level=3, parent_code="ENG-LEXA",
        description="形容词的比较等级: 原级、比较级、最高级的构成与用法",
        keywords=["形容词", "比较级", "最高级",
                  "adjective", "comparative", "superlative",
                  "more", "most", "-er", "-est"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-ADJ-01", name="形容词比较等级", level=4, parent_code="ENG-LEXA-ADJ",
        description="规则变化(-er/-est, more/most)、不规则变化、as...as/not so...as/倍数表达",
        keywords=["比较级", "最高级", "原级比较", "倍数",
                  "comparative", "superlative", "as...as",
                  "the more...the more", "倍数表达"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-ADV", name="副词", level=3, parent_code="ENG-LEXA",
        description="副词的分类(时间/地点/方式/频率/程度)与句中位置",
        keywords=["副词", "频率副词", "程度副词", "方式副词",
                  "adverb", "frequency", "manner", "degree"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-ADV-01", name="副词分类与用法", level=4, parent_code="ENG-LEXA-ADV",
        description="时间副词(now/then/already)、地点副词(here/there)、方式副词(carefully)、频率副词(always/often)、程度副词(very/quite)",
        keywords=["时间副词", "地点副词", "频率副词",
                  "adverb of time", "adverb of place",
                  "adverb of frequency", "adverb of manner"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-PRON", name="代词", level=3, parent_code="ENG-LEXA",
        description="人称代词、物主代词、反身代词、指示代词、不定代词",
        keywords=["代词", "人称代词", "物主代词", "不定代词",
                  "pronoun", "personal pronoun", "possessive",
                  "reflexive", "demonstrative", "indefinite"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-PRON-01", name="人称与物主代词", level=4, parent_code="ENG-LEXA-PRON",
        description="主格/宾格(I/me)、形容词性/名词性物主代词(my/mine)、反身代词(myself)",
        keywords=["主格", "宾格", "形容词性物主代词", "名词性物主代词",
                  "subject pronoun", "object pronoun",
                  "possessive adjective", "possessive pronoun"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-PRON-02", name="指示代词与不定代词", level=4, parent_code="ENG-LEXA-PRON",
        description="this/that/these/those、some/any/every/no及其复合词(something/anything等)、each/both/all/neither/either",
        keywords=["指示代词", "不定代词", "some与any", "each与every",
                  "demonstrative", "indefinite pronoun",
                  "something", "anything", "everything", "nothing"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-NUM", name="数词", level=3, parent_code="ENG-LEXA",
        description="基数词与序数词的构成与用法",
        keywords=["数词", "基数词", "序数词",
                  "numeral", "cardinal", "ordinal",
                  "hundred", "thousand", "first", "second"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-NUM-01", name="基数词与序数词", level=4, parent_code="ENG-LEXA-NUM",
        description="基数词(1-1000+)、序数词(first-twenty-first)、日期/时间/分数/小数表达",
        keywords=["基数词", "序数词", "分数表达", "日期表达",
                  "cardinal number", "ordinal number",
                  "fraction", "date expression"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-PREP", name="介词", level=3, parent_code="ENG-LEXA",
        description="常见介词及介词短语的用法",
        keywords=[
            "介词",
            "介词短语",
            "固定搭配",
            "preposition",
            "prepositional phrase",
            "phrasal preposition",
            "collocation",
            "phrasal verb",
            "动词短语",
            "反义词",
            "同义词",
            "复现",
            "短语动词",
            "短语搭配",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-PREP-01", name="常见介词及短语", level=4, parent_code="ENG-LEXA-PREP",
        description="时间介词(at/on/in)、地点介词(at/in/on/above/below)、方式介词(by/with/in)、常见介词短语(in front of/because of等)",
        keywords=[
            "时间介词",
            "地点介词",
            "介词短语",
            "preposition of time",
            "preposition of place",
            "in front of",
            "because of",
            "in spite of",
            "antonym",
            "collocation",
            "phrase",
            "prefix",
            "suffix",
            "synonym",
            "vocabulary",
            "word",
            "word formation",
            "前缀",
            "单词",
            "反义词",
            "后缀",
            "搭配",
            "构词法",
            "短语",
            "词义辨析",
            "词根",
            "词汇",
            "词语辨析",
            "近义词",
            "选词填空",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-CONJ", name="连词", level=3, parent_code="ENG-LEXA",
        description="并列连词与从属连词的分类和用法",
        keywords=["连词", "并列连词", "从属连词",
                  "conjunction", "coordinating conjunction",
                  "subordinating conjunction"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-CONJ-01", name="并列连词与从属连词", level=4, parent_code="ENG-LEXA-CONJ",
        description="并列连词(and/but/or/so/for/nor/yet)、从属连词(because/although/when/if/unless/while/as)",
        keywords=["并列连词", "从属连词",
                  "and/but/or", "because/although/when",
                  "coordinating", "subordinating"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-ART", name="冠词", level=3, parent_code="ENG-LEXA",
        description="定冠词the、不定冠词a/an、零冠词的用法规则",
        keywords=["冠词", "定冠词", "不定冠词", "零冠词",
                  "article", "definite article", "indefinite article",
                  "zero article"],
    ),
    KnowledgeTreeSeed(
        code="ENG-LEXA-ART-01", name="定冠词、不定冠词与零冠词", level=4, parent_code="ENG-LEXA-ART",
        description="the的特指用法、a/an的泛指用法、零冠词(专有名词/不可数名词泛指/三餐/球类)",
        keywords=["定冠词the", "不定冠词a/an", "零冠词",
                  "the", "a", "an", "zero article",
                  "特指", "泛指", "specific", "generic"],
    ),

    # ═══════════════════════════════════════════════════════════════════════════════
    # ENG-SYN 句法 (L3: 4, L4: 9)
    # ═══════════════════════════════════════════════════════════════════════════════

    KnowledgeTreeSeed(
        code="ENG-SYN-COMP", name="句子成分", level=3, parent_code="ENG-SYN",
        description="主语/谓语/宾语/表语/定语/状语/补语的识别与分析",
        keywords=["句子成分", "主语", "谓语", "宾语", "表语",
                  "sentence component", "subject", "predicate",
                  "object", "predicative", "complement"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN-COMP-01", name="主语、谓语与宾语", level=4, parent_code="ENG-SYN-COMP",
        description="主语(名词/代词/动名词/不定式/从句)、谓语(及物/不及物)、宾语(直接/间接/介词宾语)",
        keywords=["主语", "谓语", "宾语", "及物动词", "不及物动词",
                  "subject", "predicate", "object",
                  "transitive", "intransitive"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN-COMP-02", name="表语、定语、状语与补语", level=4, parent_code="ENG-SYN-COMP",
        description="表语(形容词/名词/介词短语)、定语(前置/后置)、状语(时间/地点/方式/原因)、宾补/主补",
        keywords=["表语", "定语", "状语", "补语",
                  "predicative", "attributive", "adverbial",
                  "object complement", "subject complement"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN-PATT", name="基本句型", level=3, parent_code="ENG-SYN",
        description="五大基本句型: S+V, S+V+O, S+V+P, S+V+IO+DO, S+V+O+C",
        keywords=["基本句型", "五种句型", "简单句",
                  "sentence pattern", "five basic patterns",
                  "SV", "SVO", "SVP", "SVOO", "SVOC"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN-PATT-01", name="五大基本句型", level=4, parent_code="ENG-SYN-PATT",
        description="S+V(主谓)、S+V+O(主谓宾)、S+V+P(主系表)、S+V+IO+DO(主谓双宾)、S+V+O+C(主谓宾补)",
        keywords=["主谓", "主谓宾", "主系表", "双宾语", "宾语补足语",
                  "SV", "SVO", "SVP", "SVOO", "SVOC",
                  "five sentence patterns"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN-COMPCL", name="复合句", level=3, parent_code="ENG-SYN",
        description="定语从句、状语从句、名词性从句的结构与用法",
        keywords=[
            "复合句",
            "定语从句",
            "状语从句",
            "名词性从句",
            "complex sentence",
            "clause",
            "attributive clause",
            "adverbial clause",
            "noun clause",
            "improve",
            "language",
            "sentence",
            "variety",
            "句式",
            "句式拓展",
            "简单句变复合句",
            "过渡词",
            "非谓语写作",
            "高级词汇",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN-COMPCL-01", name="定语从句", level=4, parent_code="ENG-SYN-COMPCL",
        description="关系代词(which/that/who/whom/whose/as)、关系副词(when/where/why)、限制性与非限制性定语从句",
        keywords=[
            "定语从句",
            "关系代词",
            "关系副词",
            "限制性",
            "非限制性",
            "attributive clause",
            "relative pronoun",
            "relative adverb",
            "restrictive",
            "non-restrictive",
            "defining",
            "non-defining",
            "relative clause",
            "that",
            "when",
            "where",
            "which",
            "who",
            "whom",
            "whose",
            "why",
            "非限制性定语从句",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN-COMPCL-02", name="状语从句", level=4, parent_code="ENG-SYN-COMPCL",
        description="时间/条件/原因/让步/目的/结果/方式/比较/地点状语从句及引导词",
        keywords=[
            "状语从句",
            "时间从句",
            "条件从句",
            "让步从句",
            "adverbial clause",
            "time clause",
            "condition clause",
            "concession clause",
            "because",
            "although",
            "if",
            "when",
            "unless",
            "as if",
            "attributive clause",
            "even though",
            "in order that",
            "noun clause",
            "relative adverb",
            "relative pronoun",
            "since",
            "so that",
            "subordinator",
            "that",
            "what",
            "where",
            "whether",
            "which",
            "who",
            "whom",
            "whose",
            "why",
            "从句",
            "关系词",
            "名词性从句",
            "定语从句",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN-COMPCL-03", name="名词性从句", level=4, parent_code="ENG-SYN-COMPCL",
        description="主语从句(That...is)、宾语从句(I think that...)、表语从句(The fact is that...)、同位语从句(The news that...)",
        keywords=[
            "名词性从句",
            "主语从句",
            "宾语从句",
            "表语从句",
            "同位语从句",
            "noun clause",
            "subject clause",
            "object clause",
            "predicative clause",
            "appositive clause",
            "adverbial clause",
            "although",
            "as long as",
            "because",
            "even if",
            "if",
            "in case",
            "provided that",
            "that",
            "unless",
            "what",
            "whenever",
            "wherever",
            "whether",
            "状语从句",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN-SPCL", name="特殊句式", level=3, parent_code="ENG-SYN",
        description="倒装句、强调句、省略句的结构与识别",
        keywords=[
            "特殊句式",
            "倒装",
            "强调",
            "省略",
            "special sentence",
            "inversion",
            "emphasis",
            "ellipsis",
            "hardly",
            "it is that",
            "it was that",
            "neither do I",
            "no sooner",
            "not only",
            "omission",
            "only then",
            "scarcely",
            "so do I",
            "there are",
            "there be句型",
            "there is",
            "there was",
            "there were",
            "倒装句",
            "强调句",
            "省略句",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN-SPCL-01", name="倒装句", level=4, parent_code="ENG-SYN-SPCL",
        description="完全倒装(Here comes...)、部分倒装(Never have I.../Only then did.../So do I)",
        keywords=["倒装", "完全倒装", "部分倒装",
                  "inversion", "full inversion", "partial inversion",
                  "never", "hardly", "only then", "so do I"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SYN-SPCL-02", name="强调句与省略", level=4, parent_code="ENG-SYN-SPCL",
        description="强调句型(It is/was...that/who...)、do/does/did强调谓语、省略(状语从句/不定式/to/so/not替代)",
        keywords=["强调句", "省略句", "It is...that", "do强调",
                  "emphasis cleft", "it is...that",
                  "do/does/did", "ellipsis", "omission",
                  "so/not替代"],
    ),

    # ═══════════════════════════════════════════════════════════════════════════════
    # ENG-TVOI 时态与语态 (L3: 2, L4: 9)
    # ═══════════════════════════════════════════════════════════════════════════════

    KnowledgeTreeSeed(
        code="ENG-TVOI-TENSE", name="核心时态", level=3, parent_code="ENG-TVOI",
        description="一般现在/过去/将来、现在/过去进行、现在/过去完成时的构成与用法",
        keywords=[
            "时态",
            "一般现在",
            "一般过去",
            "现在完成",
            "tense",
            "simple present",
            "simple past",
            "present perfect",
            "past perfect",
            "antonym",
            "future simple",
            "had been doing",
            "have been doing",
            "is doing",
            "past continuous",
            "present continuous",
            "synonym",
            "was doing",
            "will do",
            "一般现在时",
            "一般过去时",
            "一词多义",
            "反义词辨析",
            "核心词汇",
            "熟词生义",
            "现在完成时",
            "词义辨析",
            "过去完成时",
            "近义词辨析",
            "高频词",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-TVOI-TENSE-01", name="一般现在时", level=4, parent_code="ENG-TVOI-TENSE",
        description="表示习惯/事实/真理/时刻表, 第三人称单数加-s/-es",
        keywords=["一般现在时", "第三人称单数", "习惯",
                  "simple present", "third person singular",
                  "habitual action", "general truth"],
    ),
    KnowledgeTreeSeed(
        code="ENG-TVOI-TENSE-02", name="一般过去时", level=4, parent_code="ENG-TVOI-TENSE",
        description="过去发生的动作/状态, 规则变化(-ed)与不规则变化",
        keywords=["一般过去时", "过去式", "不规则动词",
                  "simple past", "past tense", "-ed",
                  "irregular verb", "did"],
    ),
    KnowledgeTreeSeed(
        code="ENG-TVOI-TENSE-03", name="一般将来时", level=4, parent_code="ENG-TVOI-TENSE",
        description="will/shall do, be going to do, be about to do, be to do的用法与区别",
        keywords=["一般将来时", "will", "be going to",
                  "simple future", "will do", "be going to do",
                  "be about to", "be to do"],
    ),
    KnowledgeTreeSeed(
        code="ENG-TVOI-TENSE-04", name="现在进行时", level=4, parent_code="ENG-TVOI-TENSE",
        description="be+doing表示正在进行, always/constantly表示感情色彩",
        keywords=["现在进行时", "正在进行", "be doing",
                  "present continuous", "present progressive",
                  "right now", "at the moment"],
    ),
    KnowledgeTreeSeed(
        code="ENG-TVOI-TENSE-05", name="过去进行时", level=4, parent_code="ENG-TVOI-TENSE",
        description="was/were+doing表示过去某一时刻正在进行的动作",
        keywords=["过去进行时", "was doing", "were doing",
                  "past continuous", "past progressive",
                  "at that time", "when/while"],
    ),
    KnowledgeTreeSeed(
        code="ENG-TVOI-TENSE-06", name="现在完成时", level=4, parent_code="ENG-TVOI-TENSE",
        description="have/has+done表示过去发生对现在有影响或持续到现在",
        keywords=["现在完成时", "have done", "has done",
                  "present perfect", "already", "yet", "just",
                  "since", "for", "so far", "up to now"],
    ),
    KnowledgeTreeSeed(
        code="ENG-TVOI-TENSE-07", name="过去完成时", level=4, parent_code="ENG-TVOI-TENSE",
        description="had+done表示过去某时之前已完成(过去的过去)",
        keywords=["过去完成时", "had done", "过去的过去",
                  "past perfect", "had finished",
                  "by the time", "before", "after"],
    ),
    KnowledgeTreeSeed(
        code="ENG-TVOI-VOICE", name="被动语态", level=3, parent_code="ENG-TVOI",
        description="各时态被动语态的构成: be+过去分词, 主动表被动",
        keywords=[
            "被动语态",
            "be done",
            "主动表被动",
            "passive voice",
            "be + past participle",
            "get done",
            "active voice",
            "be+过去分词",
            "get+过去分词",
            "has been done",
            "is being done",
            "is done",
            "was being done",
            "was done",
            "will be done",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-TVOI-VOICE-01", name="被动语态的构成与用法", level=4, parent_code="ENG-TVOI-VOICE",
        description="一般/进行/完成时态的被动形式, get+过去分词, 主动形式表被动意义(系动词+adj)",
        keywords=["被动语态", "各时态被动", "get+过去分词", "主动表被动",
                  "passive voice", "is done", "was done",
                  "has been done", "is being done"],
    ),

    # ═══════════════════════════════════════════════════════════════════════════════
    # ENG-NFVB 非谓语动词 (L3: 3, L4: 5)
    # ═══════════════════════════════════════════════════════════════════════════════

    KnowledgeTreeSeed(
        code="ENG-NFVB-INF", name="动词不定式", level=3, parent_code="ENG-NFVB",
        description="to do作主语/宾语/表语/定语/状语/补语, 不定式的时态与语态",
        keywords=["不定式", "to do", "不定式作主语", "不定式作宾语",
                  "infinitive", "to do", "to be done",
                  "to have done", "in order to", "so as to"],
    ),
    KnowledgeTreeSeed(
        code="ENG-NFVB-INF-01", name="不定式的句法功能", level=4, parent_code="ENG-NFVB-INF",
        description="不定式作主语(It is...to do)、宾语(want/decide/hope to do)、定语(have...to do)、目的状语(in order to)、宾补(ask/tell sb to do)",
        keywords=["不定式作主语", "不定式作宾语", "不定式作状语", "不定式作补语",
                  "infinitive as subject", "infinitive as object",
                  "infinitive as adverbial", "infinitive as complement"],
    ),
    KnowledgeTreeSeed(
        code="ENG-NFVB-GER", name="动名词", level=3, parent_code="ENG-NFVB",
        description="V-ing作主语/宾语/表语, 动名词与不定式的区别",
        keywords=["动名词", "doing", "动名词作宾语",
                  "gerund", "gerund as object",
                  "enjoy doing", "finish doing", "avoid doing"],
    ),
    KnowledgeTreeSeed(
        code="ENG-NFVB-GER-01", name="动名词的用法与辨析", level=4, parent_code="ENG-NFVB-GER",
        description="只接doing的动词(enjoy/finish/avoid/mind/practice/suggest)、只接to do的动词(want/decide/hope/plan)、两者皆可但意义不同(remember/forget/stop/try/go on)",
        keywords=["接doing的动词", "接to do的动词", "remember to do/doing",
                  "stop to do/doing", "try to do/doing",
                  "verb + gerund", "verb + infinitive"],
    ),
    KnowledgeTreeSeed(
        code="ENG-NFVB-PART", name="分词", level=3, parent_code="ENG-NFVB",
        description="现在分词(-ing表主动/进行)与过去分词(-ed表被动/完成)的用法",
        keywords=["现在分词", "过去分词", "-ing", "-ed",
                  "present participle", "past participle",
                  "doing", "done", "active", "passive"],
    ),
    KnowledgeTreeSeed(
        code="ENG-NFVB-PART-01", name="分词作定语与补语", level=4, parent_code="ENG-NFVB-PART",
        description="前置/后置定语(a sleeping boy / the boy standing there)、宾补(I saw him running / I had my hair cut)",
        keywords=["分词作定语", "分词作补语", "现在分词作定语", "过去分词作定语",
                  "participle as attributive", "participle as complement",
                  "see sb doing", "have sth done"],
    ),
    KnowledgeTreeSeed(
        code="ENG-NFVB-PART-02", name="分词作状语", level=4, parent_code="ENG-NFVB-PART",
        description="分词短语作时间/原因/条件/伴随/结果状语, 独立主格结构",
        keywords=["分词作状语", "独立主格", "伴随状语",
                  "participle as adverbial",
                  "absolute construction",
                  "weather permitting", "seen from the hill"],
    ),

    # ═══════════════════════════════════════════════════════════════════════════════
    # ENG-SUBM 虚拟语气 (L3: 1, L4: 2)
    # ═══════════════════════════════════════════════════════════════════════════════

    KnowledgeTreeSeed(
        code="ENG-SUBM-COND", name="虚拟语气条件句", level=3, parent_code="ENG-SUBM",
        description="与现在/过去/将来事实相反的if条件句结构",
        keywords=["虚拟条件句", "与现在相反", "与过去相反", "与将来相反",
                  "subjunctive conditional", "unreal condition",
                  "if I were", "if I had done", "if I should/were to"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SUBM-COND-01", name="if虚拟条件句", level=4, parent_code="ENG-SUBM-COND",
        description="与现在相反(if+过去时, would do)、与过去相反(if+had done, would have done)、与将来相反(if+should/were to, would do)、混合虚拟",
        keywords=["与现在相反", "与过去相反", "混合虚拟",
                  "present unreal", "past unreal", "mixed unreal",
                  "if I were", "if I had done", "would have done"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SUBM-OTHER", name="其他虚拟用法", level=3, parent_code="ENG-SUBM",
        description="wish/as if/suggest/demand/It is time等后的虚拟语气",
        keywords=["wish虚拟", "as if虚拟", "suggest虚拟",
                  "subjunctive in wish", "subjunctive in noun clause",
                  "It is time that", "would rather"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SUBM-OTHER-01", name="wish及名词性从句中的虚拟", level=4, parent_code="ENG-SUBM-OTHER",
        description="wish+过去时(现在)/had done(过去)/would(将来); suggest/demand/insist+(should) do; It is time+过去时; as if/as though虚拟",
        keywords=["wish虚拟", "suggest虚拟", "as if虚拟", "It is time",
                  "wish + past tense", "wish + had done",
                  "suggest + (should) do", "as if + past tense"],
    ),

    # ═══════════════════════════════════════════════════════════════════════════════
    # ENG-SKILL 语言技能 (L3: 4, L4: 12)
    # ═══════════════════════════════════════════════════════════════════════════════

    KnowledgeTreeSeed(
        code="ENG-SKILL-LIS", name="听力理解", level=3, parent_code="ENG-SKILL",
        description="听力技能: 获取关键信息、理解主旨大意、推断说话者意图",
        keywords=[
            "听力",
            "听懂",
            "获取信息",
            "主旨",
            "listening",
            "listening comprehension",
            "get information",
            "main idea",
            "conversation",
            "monologue",
            "听下面",
            "听第",
            "对话",
            "每段对话",
            "独白",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-LIS-01", name="获取信息", level=4, parent_code="ENG-SKILL-LIS",
        description="听取对话/独白中的时间、地点、人物、事件等具体信息",
        keywords=["获取信息", "关键信息", "具体细节",
                  "get information", "key detail",
                  "time", "place", "number", "name"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-LIS-02", name="理解主旨", level=4, parent_code="ENG-SKILL-LIS",
        description="把握听力材料的中心思想和话题",
        keywords=[
            "理解主旨",
            "中心思想",
            "话题",
            "main idea",
            "topic",
            "gist",
            "what is the conversation about",
            "best title",
            "mainly",
            "mainly about",
            "mainly discusses",
            "mainly talks about",
            "purpose",
            "the author's purpose",
            "the passage is mainly",
            "the text mainly",
            "theme",
            "title",
            "what is the best title",
            "what is the main",
            "主旨",
            "主题句",
            "大意",
            "标题",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-LIS-03", name="推断意图", level=4, parent_code="ENG-SKILL-LIS",
        description="根据语调、语气和上下文推断说话者的态度、意图和隐含信息",
        keywords=["推断意图", "语气", "态度", "隐含信息",
                  "infer intention", "tone", "attitude",
                  "implied meaning", "what does the speaker mean"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-SPE", name="口语表达", level=3, parent_code="ENG-SKILL",
        description="口语技能: 日常对话、主题发言、观点表达",
        keywords=["口语", "对话", "发言", "表达",
                  "speaking", "oral", "dialogue",
                  "presentation", "expression"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-SPE-01", name="日常对话", level=4, parent_code="ENG-SKILL-SPE",
        description="问候、感谢、道歉、请求、建议、邀请等日常交际用语",
        keywords=["日常对话", "交际用语", "问候", "道歉",
                  "daily conversation", "greeting", "apology",
                  "suggestion", "invitation", "request"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-SPE-02", name="主题发言", level=4, parent_code="ENG-SKILL-SPE",
        description="围绕给定话题进行有组织的口头表达(描述/介绍/汇报)",
        keywords=["主题发言", "口头表达", "描述", "汇报",
                  "topic presentation", "oral report",
                  "describe", "introduce", "talk about"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-SPE-03", name="观点表达", level=4, parent_code="ENG-SKILL-SPE",
        description="表达个人观点、进行论证、参与讨论与辩论",
        keywords=["观点表达", "论证", "讨论", "辩论",
                  "express opinion", "argue", "debate",
                  "discuss", "in my opinion", "I think"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-REA", name="阅读技能", level=3, parent_code="ENG-SKILL",
        description="阅读技能: 快速阅读、细节理解、推理判断",
        keywords=[
            "阅读",
            "阅读技能",
            "快速阅读",
            "细节理解",
            "reading",
            "reading comprehension",
            "reading skill",
            "skimming",
            "scanning",
            "inference",
            "comprehension",
            "passage",
            "read the following",
            "read the passage",
            "七选五",
            "主旨",
            "推理",
            "根据短文",
            "理解",
            "阅读下列",
            "阅读下面",
            "阅读短文",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-REA-01", name="快速阅读", level=4, parent_code="ENG-SKILL-REA",
        description="略读(skimming)获取大意、寻读(scanning)定位信息",
        keywords=["快速阅读", "略读", "寻读", "大意",
                  "skimming", "scanning", "fast reading",
                  "get the main idea", "locate information"],
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-REA-02", name="细节理解", level=4, parent_code="ENG-SKILL-REA",
        description="定位关键信息、识别同义替换、匹配事实细节",
        keywords=[
            "细节理解",
            "定位",
            "同义替换",
            "信息匹配",
            "detail comprehension",
            "locate",
            "paraphrase",
            "match information",
            "fact finding",
            "according to",
            "aim",
            "example",
            "except",
            "fact",
            "from the passage",
            "in paragraph",
            "in the passage",
            "it can be learned",
            "mentioned",
            "not true",
            "stated",
            "true",
            "we can learn",
            "we know that",
            "what is",
            "which of the following",
            "定位关键词",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-REA-03", name="推理判断", level=4, parent_code="ENG-SKILL-REA",
        description="推断作者态度、写作目的、隐含意义和文章出处",
        keywords=[
            "推理判断",
            "态度",
            "目的",
            "隐含意义",
            "inference",
            "attitude",
            "purpose",
            "implied meaning",
            "author's intention",
            "author",
            "can be inferred",
            "conclude",
            "imply",
            "infer",
            "it can be concluded",
            "learn from",
            "most likely",
            "most probably",
            "probably",
            "suggest",
            "the author's attitude",
            "the writer's attitude",
            "what can we conclude",
            "what can we infer",
            "what does the author imply",
            "what does the writer suggest",
            "where is the text taken",
            "写作目的",
            "判断",
            "推断",
            "推理",
            "隐含",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-WRI", name="写作技能", level=3, parent_code="ENG-SKILL",
        description="写作技能: 应用文写作、读后续写、观点论述",
        keywords=[
            "写作",
            "写作技能",
            "应用文",
            "续写",
            "writing",
            "writing skill",
            "practical writing",
            "continuation writing",
            "composition",
            "essay",
            "letter",
            "write",
            "书信",
            "书面表达",
            "作文",
            "假定你是",
            "假设你是",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-WRI-01", name="应用文写作", level=4, parent_code="ENG-SKILL-WRI",
        description="书信(建议/邀请/感谢/道歉/申请/投诉)、通知、演讲稿的格式与写作",
        keywords=[
            "应用文",
            "书信",
            "通知",
            "演讲稿",
            "practical writing",
            "letter",
            "notice",
            "speech",
            "email",
            "announcement",
            "格式",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-WRI-02", name="读后续写", level=4, parent_code="ENG-SKILL-WRI",
        description="根据给定材料合理续写情节, 注意人物心理/动作/环境描写, 与原文风格一致",
        keywords=[
            "读后续写",
            "情节续写",
            "人物描写",
            "环境描写",
            "continuation writing",
            "plot continuation",
            "character description",
            "scene description",
            "动作",
            "心理",
            "情节",
            "描写",
            "续写",
        ]
    ),
    KnowledgeTreeSeed(
        code="ENG-SKILL-WRI-03", name="观点论述", level=4, parent_code="ENG-SKILL-WRI",
        description="提出观点、列举论据、总结结论的议论性写作",
        keywords=["观点论述", "议论", "论据", "结论",
                  "argumentative writing", "opinion essay",
                  "thesis", "evidence", "conclusion"],
    ),

    # ═══════════════════════════════════════════════════════════════════════════════
    # ENG-THEME 主题语境 (L3: 3, L4: 12)
    # ═══════════════════════════════════════════════════════════════════════════════

    KnowledgeTreeSeed(
        code="ENG-THEME-SELF", name="人与自我", level=3, parent_code="ENG-THEME",
        description="个人生活、身心健康、学习与成长、职业规划",
        keywords=["人与自我", "个人生活", "身心健康", "成长",
                  "man and self", "personal life", "health",
                  "growth", "career planning"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-SELF-01", name="个人生活", level=4, parent_code="ENG-THEME-SELF",
        description="日常生活、兴趣爱好、家庭与朋友、个人经历",
        keywords=["个人生活", "日常生活", "兴趣爱好", "家庭",
                  "personal life", "daily life", "hobby",
                  "family", "friend", "experience"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-SELF-02", name="身心健康", level=4, parent_code="ENG-THEME-SELF",
        description="身体健康、心理健康、情绪管理、健康生活方式",
        keywords=["身心健康", "健康", "情绪", "生活方式",
                  "physical health", "mental health",
                  "emotion", "healthy lifestyle", "well-being"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-SELF-03", name="学习与成长", level=4, parent_code="ENG-THEME-SELF",
        description="学习方法、学习策略、自我提升、面对挑战与挫折",
        keywords=["学习", "成长", "方法", "挑战",
                  "learning", "growth", "study method",
                  "self-improvement", "challenge"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-SELF-04", name="职业规划", level=4, parent_code="ENG-THEME-SELF",
        description="职业选择、职业理想、能力培养、人生规划",
        keywords=["职业", "规划", "理想", "能力",
                  "career", "planning", "profession",
                  "ambition", "ability"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-SOCI", name="人与社会", level=3, parent_code="ENG-THEME",
        description="社会服务与人际关系、文学艺术、历史与文化、科学与技术",
        keywords=["人与社会", "社会", "文化", "科技",
                  "man and society", "social service",
                  "culture", "science", "technology"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-SOCI-01", name="社会服务与人际关系", level=4, parent_code="ENG-THEME-SOCI",
        description="志愿服务、社区服务、人际交往、跨文化沟通",
        keywords=["社会服务", "人际关系", "志愿", "跨文化",
                  "social service", "volunteer", "interpersonal",
                  "cross-cultural", "communication"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-SOCI-02", name="文学艺术", level=4, parent_code="ENG-THEME-SOCI",
        description="文学作品赏析、艺术形式(音乐/绘画/电影)、文化表达",
        keywords=["文学", "艺术", "音乐", "电影",
                  "literature", "art", "music", "film",
                  "painting", "cultural expression"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-SOCI-03", name="历史与文化", level=4, parent_code="ENG-THEME-SOCI",
        description="中外历史、文化遗产、传统节日、风俗习惯",
        keywords=["历史", "文化", "传统", "节日",
                  "history", "culture", "heritage",
                  "tradition", "festival", "custom"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-SOCI-04", name="科学与技术", level=4, parent_code="ENG-THEME-SOCI",
        description="科技发展、信息技术、人工智能、太空探索、医学进步",
        keywords=["科学", "技术", "人工智能", "信息",
                  "science", "technology", "AI", "information",
                  "space", "medicine", "innovation"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-NATR", name="人与自然", level=3, parent_code="ENG-THEME",
        description="自然环境、环境保护、灾害防范、宇宙探索",
        keywords=["人与自然", "自然", "环境", "生态",
                  "man and nature", "natural environment",
                  "ecology", "conservation"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-NATR-01", name="自然环境", level=4, parent_code="ENG-THEME-NATR",
        description="地理地貌、气候天气、动植物、生态系统",
        keywords=["自然环境", "气候", "动植物", "生态",
                  "natural environment", "climate", "weather",
                  "wildlife", "ecosystem", "geography"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-NATR-02", name="环境保护", level=4, parent_code="ENG-THEME-NATR",
        description="污染治理、资源节约、可持续发展、绿色生活",
        keywords=["环保", "污染", "可持续发展", "绿色",
                  "environmental protection", "pollution",
                  "sustainability", "green living", "recycle"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-NATR-03", name="灾害防范", level=4, parent_code="ENG-THEME-NATR",
        description="自然灾害(地震/洪水/台风)的成因、预防与应对措施",
        keywords=["灾害", "地震", "洪水", "预防",
                  "disaster", "earthquake", "flood",
                  "typhoon", "prevention", "emergency"],
    ),
    KnowledgeTreeSeed(
        code="ENG-THEME-NATR-04", name="宇宙探索", level=4, parent_code="ENG-THEME-NATR",
        description="太阳系、航天科技、太空探索成就、地外生命",
        keywords=["宇宙", "太空", "航天", "探索",
                  "universe", "space", "spacecraft",
                  "exploration", "solar system", "astronaut"],
    ),

    # ═══════════════════════════════════════════════════════════════════════════════
    # ENG-DISC 语篇类型 (L3: 1, L4: 6)
    # ═══════════════════════════════════════════════════════════════════════════════

    KnowledgeTreeSeed(
        code="ENG-DISC-TYPES", name="常见语篇类型", level=3, parent_code="ENG-DISC",
        description="课标要求掌握的六种常见语篇类型: 记叙文/说明文/议论文/应用文/新闻报道/对话与访谈",
        keywords=["语篇类型", "文体", "记叙文", "说明文", "议论文",
                  "text type", "genre", "narrative",
                  "expository", "argumentative"],
    ),
    KnowledgeTreeSeed(
        code="ENG-DISC-TYPES-01", name="记叙文", level=4, parent_code="ENG-DISC-TYPES",
        description="以时间顺序叙述事件, 包含人物/时间/地点/起因/经过/结果六要素",
        keywords=["记叙文", "叙事", "六要素", "时间顺序",
                  "narrative", "narration", "story",
                  "plot", "character", "setting"],
    ),
    KnowledgeTreeSeed(
        code="ENG-DISC-TYPES-02", name="说明文", level=4, parent_code="ENG-DISC-TYPES",
        description="客观介绍事物/事理, 常用定义/分类/举例/比较/因果等说明方法",
        keywords=["说明文", "说明方法", "客观", "介绍",
                  "expository", "exposition", "definition",
                  "classification", "comparison", "cause and effect"],
    ),
    KnowledgeTreeSeed(
        code="ENG-DISC-TYPES-03", name="议论文", level=4, parent_code="ENG-DISC-TYPES",
        description="提出论点→论据→论证→结论, 表达立场与观点",
        keywords=["议论文", "论点", "论据", "论证",
                  "argumentative", "argumentation",
                  "thesis", "evidence", "reasoning", "conclusion"],
    ),
    KnowledgeTreeSeed(
        code="ENG-DISC-TYPES-04", name="应用文", level=4, parent_code="ENG-DISC-TYPES",
        description="具有实用目的的文体: 书信/通知/广告/说明书/简历/日程安排等",
        keywords=["应用文", "书信", "通知", "广告",
                  "practical writing", "letter", "notice",
                  "advertisement", "instruction", "resume"],
    ),
    KnowledgeTreeSeed(
        code="ENG-DISC-TYPES-05", name="新闻报道", level=4, parent_code="ENG-DISC-TYPES",
        description="新闻的倒金字塔结构(导语→主体→背景), 客观报道事实",
        keywords=["新闻", "报道", "导语", "倒金字塔",
                  "news", "report", "headline", "lead",
                  "journalism", "inverted pyramid"],
    ),
    KnowledgeTreeSeed(
        code="ENG-DISC-TYPES-06", name="对话与访谈", level=4, parent_code="ENG-DISC-TYPES",
        description="口语化语篇, 包含问答形式、话轮转换、语气词等特征",
        keywords=["对话", "访谈", "问答", "话轮",
                  "dialogue", "interview", "conversation",
                  "Q&A", "turn-taking", "oral discourse"],
    ),
]
