import json
import os

golden_path = "test/annotations/golden/math_real_golden.json"

golden = {
    "filename": "2026北京朝阳高一（上）期末数学（教师版）.pdf",
    "created_at": "2026-08-11T00:00:00Z",
    "annotator": "human_golden",
    "version": "3.0",
    "postprocessed": False,
    "l1_fixture": "l1_snapshot_math_real_ppsv3.json",
    "questions": [
        {"question_number": "2", "question_type": "single_choice", "section_id": "选择题", "stem_line_ids": ["P1L009"], "options_line_ids": {"A": ["P1L010"], "B": ["P1L010"], "C": ["P1L010"], "D": ["P1L010"]}, "answer": "C", "answer_line_ids": ["P5L003"], "explanation_line_ids": [], "answer_source": "document_answer_table", "explanation_source": "llm_fallback", "expected_content": {"stem": "下列函数中，在定义域内单调递减且值域为(0,+∞)的是", "options": {"A": "y=-x", "B": "y=1/x", "C": "y=2^{-x}", "D": "y=log_{0.5}x"}, "answer": "C"}, "expected_anchor": {"stem_line_ids": ["P1L009"], "options_line_ids": ["P1L010"], "answer_line_ids": ["P5L003"], "explanation_line_ids": []}, "difficulty": 2, "score": 5.0, "knowledge_points": ["函数单调性", "函数值域"], "confidence": 1.0, "source_page": 1},
        {"question_number": "3", "question_type": "single_choice", "section_id": "选择题", "stem_line_ids": ["P1L011"], "options_line_ids": {"A": ["P1L012"], "B": ["P1L012"], "C": ["P1L012"], "D": ["P1L012"]}, "answer": "B", "answer_line_ids": ["P5L003"], "explanation_line_ids": [], "answer_source": "document_answer_table", "explanation_source": "llm_fallback", "expected_content": {"stem": "命题\"∀x>0，都有sinx<x\"的否定为", "options": {"A": "∃x>0，使得sinx<x", "B": "∃x>0，使得sinx≥x", "C": "∀x>0，都有sinx≥x", "D": "∀x>0，都有sinx>x"}, "answer": "B"}, "expected_anchor": {"stem_line_ids": ["P1L011"], "options_line_ids": ["P1L012"], "answer_line_ids": ["P5L003"], "explanation_line_ids": []}, "difficulty": 1, "score": 5.0, "knowledge_points": ["命题否定", "逻辑量词"], "confidence": 1.0, "source_page": 1},
        {"question_number": "5", "question_type": "single_choice", "section_id": "选择题", "stem_line_ids": ["P1L013"], "options_line_ids": {"A": ["P1L014"], "B": ["P1L014"], "C": ["P1L014"], "D": ["P1L014"]}, "answer": "A", "answer_line_ids": ["P5L003"], "explanation_line_ids": [], "answer_source": "document_answer_table", "explanation_source": "llm_fallback", "expected_content": {"stem": "已知a=3^0.1，b=log_3(10)，c=log_{1/2}(2)，则", "options": {"A": "c<a<b", "B": "b<c<a", "C": "c<b<a", "D": "a<b<c"}, "answer": "A"}, "expected_anchor": {"stem_line_ids": ["P1L013"], "options_line_ids": ["P1L014"], "answer_line_ids": ["P5L003"], "explanation_line_ids": []}, "difficulty": 2, "score": 5.0, "knowledge_points": ["指数函数", "对数函数", "大小比较"], "confidence": 1.0, "source_page": 1},
        {"question_number": "8", "question_type": "single_choice", "section_id": "选择题", "stem_line_ids": ["P1L023"], "options_line_ids": {"A": ["P2L001"], "B": ["P2L001"], "C": ["P2L001"], "D": ["P2L001"]}, "answer": "C", "answer_line_ids": ["P5L003"], "explanation_line_ids": [], "answer_source": "document_answer_table", "explanation_source": "llm_fallback", "expected_content": {"stem": "\"φ=2kπ-π/2(k∈Z)\"是\"函数f(x)=sin(2x+φ)在[-π/2,0]上单调递减\"的", "options": {"A": "充分不必要条件", "B": "必要不充分条件", "C": "充分必要条件", "D": "既不充分也不必要条件"}, "answer": "C"}, "expected_anchor": {"stem_line_ids": ["P1L023"], "options_line_ids": ["P2L001"], "answer_line_ids": ["P5L003"], "explanation_line_ids": []}, "difficulty": 3, "score": 5.0, "knowledge_points": ["三角函数单调性", "充分必要条件"], "confidence": 1.0, "source_page": 1},
        {"question_number": "9", "question_type": "single_choice", "section_id": "选择题", "stem_line_ids": ["P2L002"], "options_line_ids": {"A": ["P2L003"], "B": ["P2L003"], "C": ["P2L003"], "D": ["P2L003"]}, "answer": "D", "answer_line_ids": ["P5L003"], "explanation_line_ids": [], "answer_source": "document_answer_table", "explanation_source": "llm_fallback", "expected_content": {"stem": "在声学中，声音的强度级L(分贝）与声强I（瓦/平方米）的关系为：L=10lg(I/I₀)，其中常数I₀是基准声强。某工厂声音的强度级为90(分贝），现在传播途中设置吸音屏障，可使声强降为原来的1/4，则声音的强度级约降为", "options": {"A": "77分贝", "B": "80分贝", "C": "82分贝", "D": "84分贝"}, "answer": "D"}, "expected_anchor": {"stem_line_ids": ["P2L002"], "options_line_ids": ["P2L003"], "answer_line_ids": ["P5L003"], "explanation_line_ids": []}, "difficulty": 2, "score": 5.0, "knowledge_points": ["对数运算", "声学应用"], "confidence": 1.0, "source_page": 2},
        {"question_number": "10", "question_type": "single_choice", "section_id": "选择题", "stem_line_ids": ["P2L004"], "options_line_ids": {"A": ["P2L005"], "B": ["P2L005"], "C": ["P2L005"], "D": ["P2L005"]}, "answer": "D", "answer_line_ids": ["P5L003"], "explanation_line_ids": [], "answer_source": "document_answer_table", "explanation_source": "llm_fallback", "expected_content": {"stem": "已知集合U={n|1≤n≤2026,n∈N*}，集合M⊆U，且M中至少有两个元素。若对于M中的任意两个不同的元素x和y，都有|x-y|≥3，则M中元素个数的最大值是", "options": {"A": "506", "B": "507", "C": "675", "D": "676"}, "answer": "D"}, "expected_anchor": {"stem_line_ids": ["P2L004"], "options_line_ids": ["P2L005"], "answer_line_ids": ["P5L003"], "explanation_line_ids": []}, "difficulty": 4, "score": 5.0, "knowledge_points": ["集合", "组合最值"], "confidence": 1.0, "source_page": 2},
        {"question_number": "11", "question_type": "fill_blank", "section_id": "填空题", "stem_line_ids": ["P2L008"], "options_line_ids": {}, "answer": "√2/2", "answer_line_ids": ["P5L005"], "explanation_line_ids": [], "answer_source": "document_answer_table", "explanation_source": "llm_fallback", "expected_content": {"stem": "sin(3π/4)=______", "options": {}, "answer": "√2/2"}, "expected_anchor": {"stem_line_ids": ["P2L008"], "answer_line_ids": ["P5L005"], "explanation_line_ids": []}, "difficulty": 1, "score": 5.0, "knowledge_points": ["三角函数", "特殊角"], "confidence": 1.0, "source_page": 2},
        {"question_number": "13", "question_type": "fill_blank", "section_id": "填空题", "stem_line_ids": ["P2L010"], "options_line_ids": {}, "answer": "7", "answer_line_ids": ["P5L005"], "explanation_line_ids": [], "answer_source": "document_answer_table", "explanation_source": "llm_fallback", "expected_content": {"stem": "已知x>0，则x+(x+9)/x的最小值为______", "options": {}, "answer": "7"}, "expected_anchor": {"stem_line_ids": ["P2L010"], "answer_line_ids": ["P5L005"], "explanation_line_ids": []}, "difficulty": 2, "score": 5.0, "knowledge_points": ["均值不等式", "最值"], "confidence": 1.0, "source_page": 2}
    ]
}

with open(golden_path, "w", encoding="utf-8") as f:
    json.dump(golden, f, ensure_ascii=False, indent=2)

print("Golden file created with %d questions" % len(golden["questions"]))
